version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: blackgpt
      POSTGRES_USER: blackgpt
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blackgpt"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://blackgpt:password@db:5432/blackgpt?schema=public
      REDIS_URL: redis://redis:6379
      PORT: 3000
      JWT_SECRET: dev-secret-change-in-production
      DEMO_MODE: "false"
      LOG_LEVEL: info
      ENABLE_PROVENANCE_VALIDATION: "true"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
    command: sh -c "npx prisma migrate deploy && npm run dev"

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3000/api/v1

volumes:
  postgres_data:
  redis_data:
