version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: blackgpt-db
    environment:
      POSTGRES_USER: blackgpt
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blackgpt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blackgpt"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: blackgpt-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: blackgpt-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://blackgpt:password@db:5432/blackgpt
      REDIS_URL: redis://redis:6379
      PORT: 3000
      JWT_SECRET: change-this-in-production
      DEMO_MODE: "true"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm start"

  # Frontend
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: blackgpt-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
